In [29]:
import numpy as np

In [41]:
a = np.arange(12, 24)
a.shape

(12,)

In [42]:
a0 = a.reshape(2, 6)
a1 = a.reshape(3, 4)
a2 = a.reshape(4, 3)
a3 = a.reshape(6, 2)
a4 = a.reshape(12, 1)

In [44]:
a0.shape, a1.shape, a2.shape, a3.shape, a4.shape

((2, 6), (3, 4), (4, 3), (6, 2), (12, 1))

In [45]:
a5 = a.reshape(2, -1)
a6 = a.reshape(3, -1)
a7 = a.reshape(4, -1)
a8 = a.reshape(-1, 2)
a9 = a.reshape(-1, 1)

In [46]:
a5.shape, a6.shape, a7.shape, a8.shape, a9.shape

((2, 6), (3, 4), (4, 3), (6, 2), (12, 1))


**4.** Ответ - да, массив Numpy, состоящий из одного столбца и 12 строк -  это одномерный массив.

In [48]:
m1 = np.random.randn(3, 4)
m1

array([[-0.65035305,  1.66722717,  0.21511875, -1.52087001],
       [-0.75225   , -0.16369396,  0.1682035 , -0.07986287],
       [ 1.0221418 ,  0.52098672, -0.92003847, -0.00740565]])

In [49]:
m1.size

12

In [50]:
m2 = m1.flatten()
m2

array([-0.65035305,  1.66722717,  0.21511875, -1.52087001, -0.75225   ,
       -0.16369396,  0.1682035 , -0.07986287,  1.0221418 ,  0.52098672,
       -0.92003847, -0.00740565])

In [51]:
m2.size

12

In [88]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [82]:
b = np.array([i for i in range(20, 1, -2)])
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [90]:
a.size == b.size

True

In [91]:
a.shape == b.shape

True

In [92]:
a.ndim == b.ndim

True

In [93]:
a == b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

**7.** Ответ - разницы нет, массивы a и b - идентичны

In [107]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [108]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [109]:
c = np.vstack((a, b))
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [110]:
c.size

10

In [114]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [115]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])